url: http://arnolanglade.github.io/
baseurl: .

# Site settings
title: Arnaud Langlade - Software engineer
author: Arnaud Langlade
description: "Arnaud Langlade, software engineer. I really enjoy understanding business problems thanks to event storming and example mapping and solving them #BDD #TDD #DDD"
twitter_username: arnolanglade